# Generated by Django 5.0.2 on 2024-03-06 19:32

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(max_length=10, validators=[core.utils.validators.HexColorValidator]),
        ),
    ]
