# Generated by Django 5.0.2 on 2024-03-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EXP', 'Expense'), ('INC', 'Income'), ('TRA', 'Transfert')], default='EXP', max_length=16)),
                ('category', models.CharField(choices=[('Food_Drinks', 'Food & Drinks'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Household', 'Household'), ('Shopping', 'Shopping'), ('Vehicule', 'Vehicule'), ('Events', 'Life Events'), ('Entertainment', 'Entertainment'), ('Comm_Tec', 'Communication & Technology'), ('Financials', 'Financial Expenses'), ('Investments', 'Investments'), ('Income', 'Income'), ('Others', 'Others')], max_length=48)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NOK', 'Norwegian Krone'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('RUB', 'Russian Ruble'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('DKK', 'Danish Krone'), ('PLN', 'Polish Złoty'), ('IDR', 'Indonesian Rupiah'), ('THB', 'Thai Baht'), ('SAR', 'Saudi Riyal'), ('TWD', 'New Taiwan Dollar'), ('MYR', 'Malaysian Ringgit'), ('AED', 'United Arab Emirates Dirham'), ('PHP', 'Philippine Peso'), ('CZK', 'Czech Koruna'), ('HUF', 'Hungarian Forint'), ('CLP', 'Chilean Peso'), ('PKR', 'Pakistani Rupee'), ('COP', 'Colombian Peso'), ('QAR', 'Qatari Riyal'), ('BGN', 'Bulgarian Lev'), ('RON', 'Romanian Leu'), ('DOP', 'Dominican Peso'), ('KWD', 'Kuwaiti Dinar'), ('VND', 'Vietnamese Đồng'), ('PEN', 'Peruvian Sol'), ('NGN', 'Nigerian Naira'), ('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('OMR', 'Omani Rial'), ('MAD', 'Moroccan Dirham'), ('CUP', 'Cuban Peso'), ('GHS', 'Ghanaian Cedi'), ('UAH', 'Ukrainian Hryvnia'), ('JOD', 'Jordanian Dinar'), ('LKR', 'Sri Lankan Rupee'), ('UYU', 'Uruguayan Peso'), ('MOP', 'Macanese Pataca'), ('UZS', 'Uzbekistani Som'), ('BDT', 'Bangladeshi Taka'), ('LBP', 'Lebanese Pound'), ('IQD', 'Iraqi Dinar'), ('AZN', 'Azerbaijani Manat'), ('TND', 'Tunisian Dinar'), ('PAB', 'Panamanian Balboa'), ('NPR', 'Nepalese Rupee'), ('LYD', 'Libyan Dinar'), ('CRC', 'Costa Rican Colón'), ('BMD', 'Bermudian Dollar'), ('ANG', 'Netherlands Antillean Guilder'), ('BAM', 'Bosnia and Herzegovina Convertible Mark'), ('MUR', 'Mauritian Rupee'), ('MZN', 'Mozambican Metical'), ('ARS', 'Argentine Peso'), ('BYN', 'Belarusian Ruble'), ('HRK', 'Croatian Kuna'), ('FJD', 'Fijian Dollar'), ('BBD', 'Barbados Dollar')], max_length=5)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
