# Generated by Django 5.0.2 on 2024-03-06 19:32

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=19, validators=[core.utils.validators.TransactionAmountValidator]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Household', 'Household'), ('Shopping', 'Shopping'), ('Vehicule', 'Vehicule'), ('Life Events', 'Life Events'), ('Entertainment', 'Entertainment'), ('Communication & Technology', 'Communication & Technology'), ('Financial Expenses', 'Financial Expenses'), ('Investments', 'Investments'), ('Income', 'Income'), ('Others', 'Others')], max_length=48),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(validators=[core.utils.validators.TransactionTimeValidator]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
